# Generated by Django 3.1.4 on 2021-10-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_subjectmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='c2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=300)),
                ('op1', models.CharField(max_length=300)),
                ('op2', models.CharField(max_length=300)),
                ('op3', models.CharField(max_length=300)),
                ('op4', models.CharField(max_length=300)),
                ('ans', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='queModel',
            new_name='c1Model',
        ),
    ]
