# Generated by Django 3.1.4 on 2021-10-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_auto_20211010_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='b1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=300, null=True)),
                ('op1', models.CharField(max_length=300, null=True)),
                ('op2', models.CharField(max_length=300, null=True)),
                ('op3', models.CharField(max_length=300, null=True)),
                ('op4', models.CharField(max_length=300, null=True)),
                ('ans', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='b2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=300, null=True)),
                ('op1', models.CharField(max_length=300, null=True)),
                ('op2', models.CharField(max_length=300, null=True)),
                ('op3', models.CharField(max_length=300, null=True)),
                ('op4', models.CharField(max_length=300, null=True)),
                ('ans', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='m1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=300, null=True)),
                ('op1', models.CharField(max_length=300, null=True)),
                ('op2', models.CharField(max_length=300, null=True)),
                ('op3', models.CharField(max_length=300, null=True)),
                ('op4', models.CharField(max_length=300, null=True)),
                ('ans', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='m2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=300, null=True)),
                ('op1', models.CharField(max_length=300, null=True)),
                ('op2', models.CharField(max_length=300, null=True)),
                ('op3', models.CharField(max_length=300, null=True)),
                ('op4', models.CharField(max_length=300, null=True)),
                ('ans', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='p1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=300, null=True)),
                ('op1', models.CharField(max_length=300, null=True)),
                ('op2', models.CharField(max_length=300, null=True)),
                ('op3', models.CharField(max_length=300, null=True)),
                ('op4', models.CharField(max_length=300, null=True)),
                ('ans', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='p2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=300, null=True)),
                ('op1', models.CharField(max_length=300, null=True)),
                ('op2', models.CharField(max_length=300, null=True)),
                ('op3', models.CharField(max_length=300, null=True)),
                ('op4', models.CharField(max_length=300, null=True)),
                ('ans', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='c3Model',
        ),
        migrations.DeleteModel(
            name='c4Model',
        ),
        migrations.AlterField(
            model_name='c2model',
            name='ans',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='c2model',
            name='op1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='c2model',
            name='op2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='c2model',
            name='op3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='c2model',
            name='op4',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='c2model',
            name='que',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
