# Generated by Django 3.1.4 on 2021-10-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_auto_20211011_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('marks', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='subjectModel',
        ),
    ]
