# Generated by Django 3.1.4 on 2021-10-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
